name: Valdtech SSH Deploy
on: workflow_dispatch
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_REMOTE_HOST }}
        username: ${{ secrets.SSH_REMOTE_USER }}
        password: ${{ secrets.SSH_REMOTE_PASSWORD }}
        port: ${{ secrets.SSH_REMOTE_PORT }}
        script: |
          cd ..
          cd /home/docker
          docker login ghcr.io --username ${{ secrets.REGISTRY_USER }} --password ${{ secrets.TOKEN }}
          docker pull ghcr.io/valdtechsso/dnetblazor:master
          docker compose -f dnetblazor-docker-compose.yaml stop
          docker rm $(docker ps --filter status=exited -q)
          docker rmi $(docker images --filter "dangling=true" -q --no-trunc)
          docker compose -f dnetblazor-docker-compose.yaml up -d